npm package
This fixes the build and adds an npm package. I had to add
LD_LIBRARY_PATH to fiber-shim because it fails to load if coroutine.so
is not in your current working directory. This also uses a better
heuristic for determining if fiber-shim was used.

Also the library is now just called `fibers` when used in the context of
node.

diff --git a/bin/fiber-shim b/bin/fiber-shim
--- a/bin/fiber-shim
+++ b/bin/fiber-shim
@@ -1,7 +1,24 @@
 #!/bin/bash
+
+# assume fibers.node and coroutine.so are in same directory
+if [[ -e `dirname "$0"`/../src/fibers.node ]]; then
+  FIBERS_ROOT=`dirname "$0"`/../src
+else
+  FIBERS_ROOT=`node --vars | egrep ^NODE_PREFIX: | cut -c14-`/lib/node/.npm/fibers/active/package/src
+  if [[ ! -e "$FIBERS_ROOT/fibers.node" ]]; then
+    echo "Could not find the coroutine shim!" 1>&2
+    exit 1
+  fi
+fi
 UNAME=`uname`
 if [[ "$UNAME" == "Linux" ]]; then
-  LD_PRELOAD=`pwd`/coroutine.so $@
+  FIBER_SHIM=1 \
+  LD_PRELOAD="$FIBERS_ROOT/coroutine.so" \
+  "$@"
 elif [[ "$UNAME" == "Darwin" ]]; then
-  DYLD_INSERT_LIBRARIES=`pwd`/coroutine.dylib DYLD_FORCE_FLAT_NAMESPACE=1 $@
+  FIBER_SHIM=1 \
+  DYLD_INSERT_LIBRARIES="$FIBERS_ROOT/coroutine.dylib" \
+  DYLD_FORCE_FLAT_NAMESPACE=1 \
+  DYLD_LIBRARY_PATH="$FIBERS_ROOT" \
+  "$@"
 fi
